#db_connection_string_good: "mongodb+srv://root:%s@helloworldcluster.zndnutk.mongodb.net/test"
db_connection_string: "mongodb+srv://root:%s@helloworldcluster.zndnutk.mongodb.net/test"
db_password: "WhoDoesNoteLoveMongoDb"
db_name: "threads99Db"
dsn: "postgres://127.0.0.1/go_restful?sslmode=disable&user=postgres&password=postgres"
jwt_signing_key: "LxsKJywDL5O5PvgODZhBH12KE6k2yL8E"
jwt_expiration: 240  # in hours -> 10 days.
#db_connection_string: "mongodb+srv://root:%s@helloworldcluster.zndnutk.mongodb.net/?retryWrites=true&w=majority"
password_hashing_cost: 12
server_port: 8090